# Generated by Django 2.2 on 2020-06-04 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userDNI', models.CharField(max_length=20, verbose_name='Identificación')),
                ('nombUser', models.CharField(max_length=256, null=True, verbose_name='Nombre')),
                ('apelUser', models.CharField(max_length=256, null=True, verbose_name='Apellidos')),
                ('profeUser', models.CharField(max_length=100, null=True, verbose_name='Profesion')),
                ('fotoUser', models.ImageField(default='user.png', upload_to='perfiles/img', verbose_name='Foto de perfil')),
                ('teleUser', models.CharField(max_length=20, verbose_name='Numero de telefono')),
                ('geneUser', models.CharField(choices=[('Femenino', 'F'), ('Masculino', 'M'), ('Otro', 'Otro')], default='Otro', max_length=20, verbose_name='Género')),
                ('addData', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modifiat', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
            ],
            options={
                'verbose_name': 'Datos de Usuario',
                'verbose_name_plural': 'Información',
            },
        ),
        migrations.CreateModel(
            name='HabilUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombHabil', models.CharField(max_length=100)),
                ('DescHabilidad', models.TextField(verbose_name='Descripcion de la Habilidad')),
            ],
            options={
                'verbose_name': 'Habilidades del usuario',
                'verbose_name_plural': 'Competencias',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoleName', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcrHabil', models.DecimalField(decimal_places=1, max_digits=2)),
                ('udtHabil', models.DateField(auto_now=True)),
                ('idHabil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.HabilUser')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.DatosUser')),
            ],
            options={
                'verbose_name': 'Nivel de habilidad',
                'verbose_name_plural': 'Niveles',
            },
        ),
        migrations.CreateModel(
            name='DetaRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addUser', models.DateTimeField(auto_now_add=True)),
                ('udtuser', models.DateTimeField(auto_now=True)),
                ('estaRol', models.CharField(max_length=10)),
                ('idRol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.Roles', verbose_name='Identificador de Rol')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.DatosUser')),
            ],
            options={
                'verbose_name': 'Roles de usuarios',
                'verbose_name_plural': 'Roles',
            },
        ),
    ]
