# Generated by Django 2.2 on 2020-06-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosuser',
            name='geneUser',
            field=models.CharField(choices=[('Femenino', 'F'), ('Masculino', 'M'), ('Otro', 'Otro'), ('Selecciona...', 'Selecciona...')], default='Selecciona...', max_length=20, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='datosuser',
            name='modifiat',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado el'),
        ),
        migrations.AlterField(
            model_name='datosuser',
            name='profeUser',
            field=models.CharField(max_length=100, null=True, verbose_name='Profesión'),
        ),
        migrations.AlterField(
            model_name='datosuser',
            name='teleUser',
            field=models.CharField(max_length=20, verbose_name='Número de telefono'),
        ),
    ]
