# Generated by Django 2.2 on 2020-06-04 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userdata', '0002_auto_20200604_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategProye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lenguaje', models.CharField(max_length=200, null=True, verbose_name='Lenguaje de progamacion')),
                ('motorDB', models.CharField(max_length=200, null=True, verbose_name='Nombre de la base de datos')),
                ('arquitectura', models.CharField(max_length=200, null=True, verbose_name='Tipo de arquitectura de software')),
            ],
            options={
                'verbose_name': 'categoria del proyecto',
                'verbose_name_plural': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='TipoDocu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombDoc', models.CharField(max_length=200, null=True, verbose_name='tipo de documento')),
            ],
            options={
                'verbose_name': 'tipo de documento',
                'verbose_name_plural': 'Tipo de Documento',
            },
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombProy', models.CharField(max_length=200, null=True, verbose_name='Nombre del proyecto')),
                ('descProy', models.CharField(max_length=200, null=True, verbose_name='Descripcion del proyecto')),
                ('imgProy', models.ImageField(default='proyecto.png', upload_to='img/perfiles', verbose_name='Foto del Proyecto')),
                ('fechaIni', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de inicio')),
                ('fechaFin', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha fin')),
                ('urlRepo', models.TextField(max_length=200, verbose_name='Link del proyecto')),
                ('estaProy', models.CharField(max_length=45, verbose_name='Estado del proyecto')),
                ('idCategProye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.CategProye', verbose_name='Identificador de Categoria')),
            ],
            options={
                'verbose_name': 'tipo de proyectos',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='documentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombDocu', models.CharField(max_length=200, verbose_name='Nombre del documento')),
                ('pathDocu', models.FileField(max_length=45, upload_to=None, verbose_name='Ruta del documento')),
                ('idProyectos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos', verbose_name='Identificador de la tabla proyectos')),
                ('idTipoDocu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.TipoDocu', verbose_name='Identificador de tipo de documento')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.DatosUser', verbose_name='Identificador de la tabla Usuarios')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'Documento',
            },
        ),
    ]
